version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pulseid
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
  pulseid:
    container_name: pulseid
    image: pulseid:latest
    build:
      context: ./
    links:
      - mysql
    depends_on:
      - mysql  
    ports:
      - 8888:8888 
volumes:
 dbdata: